# Generated by Django 5.1.4 on 2025-01-10 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_stage', models.CharField(choices=[('1', 'NAME'), ('2', 'FOOD'), ('3', 'FINISH')], max_length=4)),
                ('owner', models.CharField(choices=[('USR', 'User'), ('BOT', 'Bot')], max_length=4)),
                ('message', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
        ),
    ]
